paypal_payment.paypal_standard_profile.*:
  type: config_entity
  label: PayPal Standard profile
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    email:
      type: text
      label: Email
    production:
      type: boolean
      label: Production Server
    autocapture:
      type: boolean
      label: Automatic Capture

paypal_payment.paypal_express_profile.*:
  type: config_entity
  label: PayPal Express profile
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    email:
      type: text
      label: Email
    production:
      type: boolean
      label: Production Server
    autocapture:
      type: boolean
      label: Automatic Capture
    username:
      type: text
      label: Username
    password:
      type: text
      label: Password
    signature:
      type: text
      label: Signature

plugin.plugin_configuration.payment_method_configuration.paypal_payment_basic:
  type: plugin.plugin_configuration.payment_method_configuration.payment_basic
