paypal_payment.paypal_standard_profile.*:
  type: config_entity
  label: PayPal Standard profile
  mapping:
    email:
      type: text
      label: Email
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label

plugin.plugin_configuration.payment_method_configuration.paypal_payment:
  type: plugin.plugin_configuration.payment_method_configuration.payment_base
  mapping:
    brand_label:
      label: Brand label
      type: text
    profile:
      label: PayPal profile
      type: text
    execute_status_id:
      label: Execute payment status
      type: string
    capture:
      label: Capture
      type: boolean
    capture_status_id:
      label: Capture payment status
      type: string
    refund:
      label: Refund
      type: boolean
    refund_status_id:
      label: Refund payment status
      type: string
